name: Android CI

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List all files in the repository
      run: |
        echo "Listing all files in the repository:"
        find . -print    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      #run: ./gradlew build
      run: ./gradlew assembleRelease
    - name: List all files in the repository
      run: |
        echo "Listing all files in the repository:"
        find . -print      
    - name: Upload APK To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: |
          app/build/outputs/apk/release/*
